const ACTIVITY_EMOJIS: { match: string; emoji: string }[] = [
  { match: "natation", emoji: "🏊" },
  { match: "nage", emoji: "🏊" },
  { match: "basket", emoji: "🏀" },
  { match: "hand", emoji: "🤾" },
  { match: "foot", emoji: "⚽" },
  { match: "volley", emoji: "🏐" },
  { match: "badminton", emoji: "🏸" },
  { match: "tennis de table", emoji: "🏓" },
  { match: "ping", emoji: "🏓" },
  { match: "tennis", emoji: "🎾" },
  { match: "course", emoji: "🏃" },
  { match: "cross", emoji: "🏃" },
  { match: "demi-fond", emoji: "🏃" },
  { match: "relais", emoji: "🏃" },
  { match: "athl", emoji: "🏃" },
  { match: "saut", emoji: "🤾" },
  { match: "gym", emoji: "🤸" },
  { match: "acrosport", emoji: "🤸" },
  { match: "danse", emoji: "💃" },
  { match: "cirque", emoji: "🎪" },
  { match: "escalade", emoji: "🧗" },
  { match: "muscu", emoji: "🏋️" },
  { match: "haltéro", emoji: "🏋️" },
  { match: "step", emoji: "🎶" },
  { match: "vélo", emoji: "🚴" },
  { match: "velo", emoji: "🚴" },
  { match: "cycl", emoji: "🚴" },
  { match: "vtt", emoji: "🚵" },
  { match: "rugby", emoji: "🏉" },
  { match: "art martia", emoji: "🥋" },
  { match: "judo", emoji: "🥋" },
  { match: "karat", emoji: "🥋" },
  { match: "lutte", emoji: "🥋" },
  { match: "boxe", emoji: "🥊" },
  { match: "escrime", emoji: "🤺" },
  { match: "ultimate", emoji: "🥏" },
  { match: "frisbee", emoji: "🥏" },
  { match: "kayak", emoji: "🛶" },
  { match: "aviron", emoji: "🚣" },
  { match: "voile", emoji: "⛵" },
  { match: "ski", emoji: "⛷️" },
  { match: "patin", emoji: "⛸️" },
  { match: "golf", emoji: "⛳" },
  { match: "yoga", emoji: "🧘" },
  { match: "orientation", emoji: "🧭" },
  { match: "randonn", emoji: "🥾" },
  { match: "surf", emoji: "🏄" },
];

/** Emoji sportif déduit du nom de l'activité renseigné par l'enseignant. */
export function activityEmoji(name: string): string {
  const normalized = (name ?? "").toLowerCase();
  return ACTIVITY_EMOJIS.find((entry) => normalized.includes(entry.match))?.emoji ?? "🎽";
}
