/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EleveRouteImport } from './routes/eleve'
import { Route as EleveIndexRouteImport } from './routes/eleve/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EleveRoute = EleveRouteImport.update({
  id: '/eleve',
  path: '/eleve',
  getParentRoute: () => rootRouteImport,
} as any)
const EleveIndexRoute = EleveIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EleveRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/eleve': typeof EleveRouteWithChildren
  '/eleve/': typeof EleveIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/eleve': typeof EleveIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/eleve': typeof EleveRouteWithChildren
  '/eleve/': typeof EleveIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/eleve' | '/eleve/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/eleve'
  id: '__root__' | '/' | '/eleve' | '/eleve/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EleveRoute: typeof EleveRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eleve': {
      id: '/eleve'
      path: '/eleve'
      fullPath: '/eleve'
      preLoaderRoute: typeof EleveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eleve/': {
      id: '/eleve/'
      path: '/'
      fullPath: '/eleve/'
      preLoaderRoute: typeof EleveIndexRouteImport
      parentRoute: typeof EleveRoute
    }
  }
}

interface EleveRouteChildren {
  EleveIndexRoute: typeof EleveIndexRoute
}

const EleveRouteChildren: EleveRouteChildren = {
  EleveIndexRoute: EleveIndexRoute,
}

const EleveRouteWithChildren = EleveRoute._addFileChildren(EleveRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EleveRoute: EleveRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
